export const questions = [
  { id: 1, question: "您的年龄段在()", name: "age", singleLine: true },
  {
    id: 2,
    question: "您的性别是()",
    name: "gender",
    noText: true,
    hasOption: true,
    options: [
      { name: "Male", value: "male", label: '男', checked: true },
      { name: "Female", value: "female", label: '女' },
    ],
    optionName: "gender",
  },
  { id: 3, question: "您所患的是()", name: "suffers" },
  { id: 4, question: "具体症状表现为()", name: "symptoms" },
  {
    id: 5,
    question: "有没有出现相关的并发症（）？具体表现为（）症状",
    name: "complicationsDetails",
    hasOption: true,
    options: [
      { name: "No", value: false, label: '不', checked: true },
      { name: "Yes", value: true, label: '是' },
    ],
    optionName: "relatedComplications",
  },
  {
    id: 6,
    question: "是否患有其他共病（）？具体是（）",
    name: "comorbiditiesDetails",
    hasOption: true,
    options: [
      { name: "No", value: false, label: '不', checked: true },
      { name: "Yes", value: true, label: '是' },
    ],
    optionName: "otherComorbidities",
  },
  {
    id: 7,
    question: "您近期有做过（）手术",
    name: "hadSurgeryRecently",
    noText: true,
    hasOption: true,
    options: [
      { name: "No", value: false, label: '不', checked: true },
      { name: "Yes", value: true, label: '是' },
    ],
    optionName: "hadSurgeryRecently",
  },
  {
    question: "您近期有做过（）检查",
    name: "hadCheckupRecently",
    noText: true,
    hasOption: true,
    options: [
      { name: "No", value: false, label: '不', checked: true },
      { name: "Yes", value: true, label: '是' },
    ],
    optionName: "hadCheckupRecently",
  },
  {
    id: 8,
    question: "身体有没有出现过浮肿情况？具体是（）部位",
    name: "experiencedEdema",
    // hasOption: true,
    // options: [
    //   { name: "No", value: false, label: '不', checked: true },
    //   { name: "Yes", value: true, label: '是' },
    // ],
    // optionName: "experiencedEdemaDetail",
  },
  {
    id: 9,
    question: "有没有出现过腹水情况（）",
    name: "hadAscites",
    optionName: "hadAscites",
    hasOption: true,
    noText: true,
    options: [
      { name: "No", value: false, label: '不', checked: true },
      { name: "Yes", value: true, label: '是' },
    ],
  },
  { id: 10, question: "近期睡眠情况（）", name: "recentSleepStatus" },
  { id: 11, question: "近期体重变化（）", name: "recentWeightChanges" },
  { id: 12, question: "近期饮食变化（）", name: "recentDietChanges" },
  { id: 13, question: "近期食量变化（）", name: "recentAppetiteChanges" },
  { id: 14, question: "吞咽情况（）", name: "swallowingStatus" },
  { id: 15, question: "近期运动情况（）", name: "recentSportsStatus" },
  {
    id: 16,
    question: "可以进行的运动强度（）",
    name: "capableExcerciseIntensity",
  },
  { id: 17, question: "食物咀嚼情况（）", name: "foodChewingStatus" },
  { id: 18, question: "手术前服用（）药物", name: "drugsTakenBeforeSurgery" },
  { id: 19, question: "手术后服用（）药物", name: "drugsTakenAfterSurgery" },
  { id: 20, question: "请描述化疗记录和化疗方案", name: "chemotherapyRecords" },
  { id: 21, question: "请描述放疗纪录和放疗方案", name: "radiotherapyRecords" },
  {
    id: 22,
    question: "请写下化疗期间用药剂量",
    name: "medicationDuringChemotherapy",
  },
  {
    id: 23,
    question: "请写下放疗期间用药剂量",
    name: "medicationDuringRadiotherapy",
  },
  {
    id: 24,
    question: "是否看过中医（）？",
    name: "seenChineseMedicine",
    optionName: "seenChineseMedicine",
    hasOption: true,
    noText: true,
    options: [
      { name: "No", value: false, label: '不', checked: true },
      { name: "Yes", value: true, label: '是' },
    ],
  },
  {
    id: 25,
    question: "是否吃过中药（）？",
    name: "takenChineseMedicine",
    optionName: "takenChineseMedicine",
    hasOption: true,
    noText: true,
    options: [
      { name: "No", value: false, label: '不', checked: true },
      { name: "Yes", value: true, label: '是' },
    ],
  },
  {
    id: 26,
    question: "请写下中药方明细和剂量（）",
    name: "chineseMedicineRecords",
  },
  {
    id: 27,
    question: "服用易瑞沙后出现哪些不良反应（）？是否恶心呕吐（）？",
    name: "sideEffectsAfterIressa",
    hasOption: true,
    options: [
      { name: "No", value: false, label: '不', checked: true },
      { name: "Yes", value: true, label: '是' },
    ],
    optionName: "nauseaAfterIressa",
  },
  {
    id: 28,
    question: "服用易瑞沙后每天的饮食是否有改善（）？具体表现为（）",
    name: "dietImprovementsAfterIressa",
    hasOption: true,
    options: [
      { name: "No", value: false, label: '不', checked: true },
      { name: "Yes", value: true, label: '是' },
    ],
    optionName: "isDietImprovedAfterIressa"
  },
  {
    id: 29,
    question: "服用易瑞沙后第二个月是否开始运动？",
    name: "exerciseInSecondMonthAfterIressa",
    optionName: "exerciseInSecondMonthAfterIressa",
    hasOption: true,
    noText: true,
    options: [
      { name: "No", value: false, label: '不', checked: true },
      { name: "Yes", value: true, label: '是' },
    ],
  },
  {
    id: 30,
    question: "是否服用多种维生素（）？如服用多种维生素请写下来（）？",
    name: "multivitaminRecords",
    hasOption: true,
    options: [
      { name: "No", value: false, label: '不', checked: true },
      { name: "Yes", value: true, label: '是' },
    ],
    optionName: "takingMultivitamins",
  },
  { id: 31, question: "近期心情变化（）", name: "recentMoodChanges" },
  { id: 32, question: "近期需要什么样的护工（）？", name: "nurseNeeded" },
];
